spring.application.name=demo
# Путь к файлу БД (создаст папку db_data и файл restaurant_db внутри проекта)
spring.datasource.url=jdbc:h2:file:./db_data/restaurant_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Настройки JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Автоматическое создание и обновление таблиц по Java-классам
spring.jpa.hibernate.ddl-auto=update
# Включаем логирование SQL в консоль, чтобы видеть, как работают наши Specifications
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Включение консоли H2 (можно будет зайти через браузер для проверки таблиц)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console